### ISSUE TITLE
 Creating Multiple Themes with Sass

### ISSUE THREAD

**Issue by zellwk** [SassConf/2015-austin-speaker-cfp#14]
# Creating Multiple Themes with Sass
## Type of Presentation (required)

[ ] Standard Length Talk
[X] Lightning Talk
[ ] Workshop
[ ] Moderated Discussion
## Description (required)

Creating a site with multiple themes at once is one challenge that many frontend developers face. It's tough to support multiple themes while keeping the code base clean. 

In this lightning talk, I'd like to share a Sass mixin that I built to make theming easy, even if you have a large number of themes with numerous options. 

You will be writing something similar to this:

``` scss
.some-element {
  @include themify () {
    color: theme(text-color);
    background: theme(background-color);
  }
}
```

And multiple themes will be created for you.

Bonus Material: 

The github repo for this theming mixin (still working on it)
## Speaker Info (required)
- Name      : Zell Liew
- Location  : Singapore
- Contact   : zellwk@gmail.com
##### Social Media:
- Twitter   : [@zellwk](https://twitter.com/zellwk)
- GitHub    : [msmarvel](https://github.com/zellwk)
- Url(s)    : [zell-weekeat.com](url to relevant sites)
##### Bio:

I'm Zell, a freelance frontend developer who specializes in using Susy for layouts. I have been working with Susy over the past year and helped many developers with their challenges on it. 

Aside from Susy, I love to tinker with Sass, create my own mixins and functions and explore how to make coding things easier and more efficient. 

Besides Susy, I also play around with JavaScript and build tools like Gulp and Grunt. 

If I'm not coding, you'll find me struggling to learn the guitar :) 
##### Photo:

![](http://www.zell-weekeat.com/wp-content/uploads/2015/05/D71_1763.jpg)

**Comment by scottkellum** [comment]
Sounds interesting and I’m reading over [your post on this](http://www.zell-weekeat.com/organizing-multiple-theme-styles-with-sass/). It would be helpful to have a project as an example of how to use this technique. I have done some work with theming SB Nations 300+ sites and we use different settings injected by Ruby into Sass files for that. Behance has also done similar things by changing a settings file for each new site. Why use this and why have a single large CSS file over a smaller file for each site? An example of using this may help me understand this better.

**Comment by zellwk** [comment]
The main advantage for this method is that we can simply write the `themify()` mixin within our components without having to split specific selectors out into a separate `_theme.scss` partial. 

This relies only on Sass and do not require any additional plugins. 

If we make a large number of themes (say 10), then the compiled stylesheet may start to get large. How large of a file should the stylesheet be before we split it up into multiple css files? When would one extra HTTP request result in a longer loading speed than 1 long css file? That's still a debate I haven't found an answer for. 

If it gets too large, like 300 in SB Nation's case, then it probably make more sense to split up the themes to reduce the number of unused selectors. The settings injected by Ruby would help tremendously then. 

Quick question: if we use Ruby, can we still use LibSass? 

I was thinking of making a gulp plugin to help split different themes into separate `theme-name.css` files so we could serve multiple css files if we wanted to, and still use LibSass for compiling. 

Another factor to think about is whether the site a page that requires all attributes of different themes to be displayed. A recent project I worked on has a home page that contains color-coded items for different sections of the site. 

If we write modular code, we have different components and it'll be difficult to split up theme attributes for every component and insert them into a `home-page.scss` or a specific home-page theme file. In that case, it might be more beneficial to have one long Css file. 

Besides, if we cache the site's CSS on the user's browser after they viewed the site for the first time, would a long CSS file vs shorter CSS files matter that much? 

These are some questions I thought would be interesting to explore, but if we go that route it might go into a full length talk. 

Would love to hear back :)

**Comment by elyseholladay** [comment]
Hi Zell!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! We thought this topic would be especially good in a more hands-on environment where everyone can follow along on their own computers!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
