### ISSUE TITLE
Rails Basics for Sassmeisters

### ISSUE THREAD

**Issue by ghost** [SassConf/2015-austin-speaker-cfp#20]
Rails Basics For Sassmeisters
## Type of Presentation (required)

[  ] Standard Length Talk
[ X ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)
- I want to give a 15-minute beginner rundown of how to use Sass in a Ruby on Rails project.  Front-end developers often end up working on a team that uses Rails, and would find it useful to understand the basics of the framework. Some topics to cover:
- Rails file/folder structure -- what is all this stuff? 
- Similarities between Sass and Ruby: variables and maps.
## Speaker Info (required)
- Name      : Lucian Kahn
- Location  : Brooklyn, NY
- Contact   : luciankahn@gmail.com
##### Social Media:
- Twitter   : [@luciankahn](https://twitter.com/luciankahn)
- GitHub    : [luciankahn](https://github.com/luciankahn)
##### Bio:

Former ESL teacher, new Ruby developer, forever Sassmeister. 
##### Photo:

![Avatar](https://scontent-lga.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/10429211_1110812795611379_1894037449477847902_n.jpg?oh=ed4ecc3e87a7765ae36a6fe03a739025&oe=559E32A0)

**Comment by elyseholladay** [comment]
Hi Lucian!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! We thought this topic would be especially good in a more hands-on environment where everyone can follow along on their own computers!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
