### ISSUE TITLE
Pardon my Sass

### ISSUE THREAD

**Issue by jonrohan** [SassConf/2015-austin-speaker-cfp#41]
# Pardon my Sass
## Type of Presentation
- [x] Standard Length Talk
- [ ] Lightning Talk
- [ ] Workshop
- [ ] Moderated Discussion
## Description

When I started working at GitHub, the CSS codebase was a mess. We had a lot of styles still in a base.css file, and only minor refactoring going on. I want to take the audience on an evolutionary tour of how we went from no-SCSS to having a complex SCSS framework, fully tested, and eventually open sourced.

I would structure my talk around these main points.
- #### Organizing
  
  Strategies we used for organizing the large sets of `.scss` files we were dealing with. Explaining some of the common pitfalls and dead-ends we reached.
- #### Testing
  
  All the linting and custom testing that we introduced to make sure our scss follows our styleguide and keeps us honest. Which includes making sure we have classnames that match each other in the html and the scss. This helps us not leave any orphaned code in the scss or the html.
- #### Sharing
  
  The decisions to eventually open source some of our `.scss` that was refactored out into a reusable framework. [primercss](http://primercss.io/)
## Speaker Info
- Name      : Jon Rohan
- Location  : Atlanta, GA
- Contact   : yes@jonrohan.codes
##### Social Media:
- Twitter   : [@jonrohan](https://twitter.com/jonrohan)
- GitHub    : [jonrohan](https://github.com/jonrohan)
- Url(s)    : [jonrohan.codes](http://jonrohan.codes/)
##### Bio:

I'm Jon Rohan, a developer on the CSS team at GitHub. For over a decade I've been a front-end developer, [working](http://jonrohan.codes/#about) on some great products. Whenever I can, I will write about various [tips and tricks](http://jonrohan.codes/fieldnotes/) that I learned in my trials and tribulations. Previously I've given [talks](http://jonrohan.codes/appearances/) on topics like [css performance](http://jonrohan.codes/appearances/#github-s-css-performance) and [icon fonts](http://jonrohan.codes/appearances/#the-making-of-octicons).

In my spare time I enjoy my garden, farmers markets, and travel.
##### Photo:

![jonrohan](https://cloud.githubusercontent.com/assets/54012/7656663/ed59838c-faf9-11e4-9649-0f9d2b69a07d.jpg)

**Comment by elyseholladay** [comment]
Hi Jon,

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
