### ISSUE TITLE
Build a Better Accordion

### ISSUE THREAD

**Issue by nickpiesco** [SassConf/2015-austin-speaker-cfp#44]
# Build a Better Accordion
## Type of Presentation (required)
- [ ] Standard Length Talk
- [x] Lightning Talk
- [ ] Workshop
- [ ] Moderated Discussion
## Description (required)

Accordions are a useful way to handle groups of nested lists when there’s not a lot of screen real estate to play with &ndash; especially handy for off-canvas navigation on mobile devices. Don’t see yourself needing to build an accordion any time soon? That’s okay! We’ll talk about things that’ll help make anything you build even more awesome:
- Semantic markup (When do I use an `<a>`? When do I use a `<button>`?)
- Animatable and non-animatable CSS properties
- Making Sass do the work for you

After laying the groundwork, I’ll walk through building a mixin that lets us add good user affordance and silky-smooth CSS animations with a single line of code.

This is a fairly beginner-level talk that also includes:
- Baseball
- Twirly things
- Sage words from a wise devops man
## Speaker Info (required)
- Name      : Nick Piesco
- Location  : Austin, TX
- Contact   : hello@nickpiesco.com
##### Social Media:
- Twitter   : [@nickpiesco](https://twitter.com/nickpiesco)
- GitHub    : [nickpiesco](https://github.com/nickpiesco)
##### Bio:

I’m a User Experience Engineer at [Bloomfire](http://bloomfire.com). Before playing with things on a computer screen for a living, I spent more than a decade on TV screens as a [meteorologist](http://bloomfire.com/blog/nick-piesco/). When I’m not nerding out about design and type, exploring other cultures through their junk food, or finding a new beer to try out, you can find me tending my license plate collection.
##### Photo:

![Nick Piesco](http://nickpiesco.com/etc/nickpiesco.jpg)

**Comment by nickpiesco** [comment]
I don’t seem to have the privileges to label this `constructive-crit`, but it’s always welcome!

**Comment by elyseholladay** [comment]
Hi Nick!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
