### ISSUE TITLE
Super Flexible Components

### ISSUE THREAD

**Issue by hagenburger** [SassConf/2015-austin-speaker-cfp#53]
# Super Flexible Components
## Type of Presentation
- [ ] Standard Length Talk  
- [x] Lightning Talk  
- [ ] Workshop  
- [ ] Moderated Discussion
## Description

Sass offers great ways for themeing. You can put colors, sizes and more into variables, calculate them via mixins and create a nice website.

In doing that, however, you’ve also generated many lines of CSS code.

Many of those theming issues can be addressed with normal CSS. `currentColor`, and calculations by scalable units are a powerful toolset. Done the right way, the quality of a component-based framework can be increased siginificantly through their use.
## Speaker Info
- Name      : Nico Hagenburger
- Location  : Berlin, Germany
- Contact   : nico@hagenburger.net
##### Social Media:
- Twitter   : [@hagenburger](https://twitter.com/hagenburger) [@LSGorg](https://twitter.com/LSGorg)
- GitHub    : [@hagenburger](https://github.com/hagenburger) [@livingstyleguide](https://github.com/livingstyleguide)
- Dribbble  : [@hagenburger](https://dribbble.com/hagenburger)
- Url(s)    : [hagenburger.net](http://www.hagenburger.net) [quotation-marks.org](http://www.quotation-marks.org) [livingstyleguide.org](http://www.livingstyleguide.org)
##### Bio:

I love Sass, have been having my love affair with it since the colon used to be on the left side of the attribute name. During the day, I work on large, maintainable code bases, style guides, and designing in the browser. Whenever I find a way to automize things, I try to create an open-source solution. It started with [Lemonade/Compass Sprites](https://github.com/hagenburger/lemonade#lemonade-is-deprecated), [Sass Quotation-Marks](http://quotation-marks.org), [Git Routines](https://github.com/hagenburger/git-routines), and the baby I spent most of my time on: the [LivingStyleGuide Gem for Sass](https://github.com/livingstyleguide/livingstyleguide/tree/v2#readme). Just recently, I put my experience on style guide APIs [into an own Gem](https://github.com/hagenburger/styleguide-api) which is already in use to keep [Eurucamp’s](http://style-guide.eurucamp.org/2015/components.html) different applications in sync.

When my computer is actually off, I’m working with interior design, including my collection of vintage subway train parts and signage. I don’t own any part of the train shown on my photo though.
##### Photo:

![Nico Hagenburger](http://www.hagenburger.net/DOWNLOADS/nico-queens.jpg)

**Comment by elyseholladay** [comment]
Hi Nico!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! 

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
