### ISSUE TITLE
Chrome Development Tools and Remote Debugging

### ISSUE THREAD

**Issue by heatherpriceonline** [SassConf/2015-austin-speaker-cfp#60]
# Chrome Development Tools and Remote Debugging
## Type of Presentation

[  ] Standard Length Talk
[X] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

How to use Chrome Development tools and remote debugging to makes front end debugging way easier. 
## Speaker Info
- Name      : Heather Price
- Location  : Blacksburg, VA
- Contact   : heather.price@modea.com
##### Social Media:
- Twitter   : [@priceheather32](https://twitter.com/priceheather32)
- GitHub    : [hprice11](https://github.com/hprice11)
##### Bio:

I am an Associate Software Engineer at Modea and Co-Lead of a 100 Girls of Code New River Valley. My life can be summed up with 3 words: Cats, Code, and Crafts. 
##### Photo:

![Avatar](https://s.gravatar.com/avatar/2ef677e0d755bca9715bb422359490f3?s=80)

**Comment by elyseholladay** [comment]
Hi Heather!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! Debugging is a topic that definitely doesn't get enough stage time, but is best learned by doing. I think this would be a perfect fit for Unconf!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
