### ISSUE TITLE
Tomorrow's CSS today

### ISSUE THREAD

**Issue by briangraves** [SassConf/2015-austin-speaker-cfp#61]
# Tomorrow's CSS today
## Type of Presentation (required)

[ x ] Standard Length Talk
[ x ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Sass is the new breeding ground for the next generation of CSS. As people use it to extend and experiment with what CSS can and should do, a lot of that functionality inevitably ends up in the CSS working drafts in one form or another. This is true from variables to color functions, custom media queries to custom selectors. Users of preprocessors have truly become the new pioneers of CSS. This talk will look at all of the different features in the CSS Level 4 working draft that have been influenced by Sass and other preprocessors, why preprocessors are important for keeping native CSS on the bleeding edge, and even dive into the use of post processors like postCSS and how they compare.
## Speaker Info (required)
- Name      : Brian Graves
- Location  : Kansas City, MO
- Contact   : bgraves@degdigital.com
##### Social Media:
- Twitter   : [@briangraves](http://www.twitter.com/briangraves)
- GitHub    : [briangravesl](https://github.com/briangraves)
- Url(s)    : [brianleegraves.com](http://www.brianleegraves.com)
##### Bio:

A UI designer and developer who's passionate about design and the process behind it, Brian is a strong proponent of iterative work, collaborative efforts, and user first design. He is currently the UI team lead at DEG where he does cross-channel design and development work for a range of major clients and brands. In addition to his  9-5, Brian has several side projects including Yeo+Lab, Responsive Email Patterns and Responsive Email Resources and speaks and writes regularly.
##### Photo:

![Avatar](http://brianleegraves.com/Headshots/Professional.jpg)

http://brianleegraves.com/Headshots/Professional.jpg

**Comment by elyseholladay** [comment]
Hi Brian!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! We love the "future CSS" topic and I think it'd be great at Unconf, where everyone can participate!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
