### ISSUE TITLE
With Our Powers Combined...

### ISSUE THREAD

**Issue by orangedrum** [SassConf/2015-austin-speaker-cfp#64]
# Living Styleguides make for better UX
## Type of Presentation (required)

[  ] Workshop
## Description (required)

From a developer's point of view, a well documented living styleguide that perfectly houses your code and properly communicates to it's other SASS constituents' how to use your beautiful styles is crucial. But did you know usability minded folks can also leverage such power?

In this workshop, I will explain how to leverage a living styleguide from a UX point of view. Our focus will be to increase a user's ability to get the experience we're aiming for. Typically, this is done with low fidelity (pencil sketches) to high fidelity (html) wireframes that are then run through a test or two to determine which direction to move forward in.  What better way to test in this manner than to use one's own living Styleguide? It is both low fidelity in the fact it is already built, and high fidelity because living styleguides are a duplicate of whatever's already "living" in your application.

The workshop will consist of:

*Forking An Example Repo
*Rapid Prototyping
*Switching Button Colors
*Effortlessly Altering Form Layouts
*Building an A/B Test or two
### Workshops: Coding Exercise (required for workshops only)

Since we'll be leveraging a living styleguide and therefore the styles and markup would theoretically already exist in our software, code won't be written as much as rearranged. Examples may include:

*Altering a Primary button's color
*Changing the layout of the markup
*Copy/Pasting existing code
## Speaker Info (required)
- Name      : Jean Kaluza
- Location  : Cocoa Beach, FL
- Contact   : jean.kaluza@orangedrum.com
##### Social Media:
- Twitter   : [@orangedrum](url to twitter account)
- GitHub    : [orangedrum](url to GitHub account)
- Url(s)    : [orangedrum.com](url to relevant sites)
##### Bio:

I live in sunny Cocoa Beach, FL. I like design and code that are based in fact and driven by data. Final products should have a certain "intelligence" to them. I have worked as a CSS developer for eight years and a UX Designer for four of them. As of this initial issue submission, I am currently seeking new endeavors.
##### Photo:

![twitter](https://cloud.githubusercontent.com/assets/4944382/7575913/e55919fe-f806-11e4-96ae-1e48aa6596fb.jpeg)

_www.orangedrum.com_

**Comment by elyseholladay** [comment]
Hi Jean!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! Style guides are hugely popular and I am sure the unique UX-focused perspective will be valuable to other UX/Designers who are not familiar with Sass styleguides!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
