### ISSUE TITLE
Dynamic Toolchains For Static Sites

### ISSUE THREAD

**Issue by endtwist** [SassConf/2015-austin-speaker-cfp#72]
# Title of Presentation
## Type of Presentation
- [x] Standard Length Talk
- or
- [x] Lightning Talk
## Description

There are dozens of static site generators available, each with it’s own APIs, syntaxes, and setup processes. Jekyll, Middleman, Hugo, Wintersmith … the list goes on and on. Often, these generators are strongly opinionated in the construction of the site, using specific templating languages and pre-processing libraries. However, with build tools for the web now so prevalent, there’s little need for a generic static site generator; with tools such as Gulp, it takes little time to put together a generator that works with your needs and requirements. I’ll show you how we put together Airframe, a static site prototyping kit, to do just that, and how easy it is to build your own.

_Outline:_
- Intro
  - The generator landscape
  - The gulp universe
- A look at Airframe
  - What is it?
  - How does it work?
  - Building your site in 60 seconds
- Building your own
  - What are the core components?
  - How do we put this all together?
  - Best practices
## Speaker Info
- Name      : Josh Gross
- Location  : NYC, NY
- Contact   : josh@planetary.io
##### Social Media:
- Twitter   : [@endtwist](https://twitter.com/endtwist)
- GitHub    : [endtwist](https://github.com/endtwist)
- Url(s)    : [gross.is](http://gross.is), [Planetary](http://planetary.io)
##### Bio:

I’m a Partner at Planetary with over 10 years of professional design and development experience for the web and mobile, having worked closely with dozens of companies such as Mozilla and Google. I’ve also worked closely with the clients and the Planetary team to help translate user need into great products. In my free time, I like to travel and restore vintage Polaroid cameras.
##### Photo:

![Avatar](https://avatars2.githubusercontent.com/u/197322?v=3&s=460)

**Comment by elyseholladay** [comment]
Hi Josh!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! Static site generators are super fun to play with and we think attendees will get a lot out of getting to actually install and use it along with you!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
