### ISSUE TITLE
A tale of Sass in a community project

### ISSUE THREAD

**Issue by karmatosed** [SassConf/2015-austin-speaker-cfp#76]
# A tale of Sass in an open source project
## Type of Presentation (required)

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

This is a story of how Sass was brought into a community open source project. _s or underscores (https://github.com/Automattic/_s) is a starter theme for WordPress begun by Automattic (the company behind WordPress.com) and then open sourced. This theme has a strong community behind it and a growing user base. All themes that Automattic make for WordPress.com use it as a starting point.

The community was demanding that Sass be added to _s. There were forks, there were pull requests, there were a lot of different opinions. The challenge was how this should be done. With so many opinions, so many ways - how did Sass get added to _s? What does Sass in _s look like? I’ll talk you through the ups, downs. It’s a tale of twists and turns and of a cast of many.

I gave a small version of this talk at a local meetup in October of last year, this is the second part looking at how the last year has changed a lot. The meetup did not record the talk, but the slides are on my speaker deck. This part two will be a complete rewrite with hindsight and where the project is now. I'll look over the past year, the community reaction and feedback. How did we automate the addition of Sass through the download site underscores.me? What are the issues with our current workflow? Where did it go wrong and where did it go right?

Then, I'll bring us around to how the next stage is shaping up. I'll be critical of the route we took with hindsight. I'll shed insight on a simplification and how we went too far to over engineering with the version we released. I'll share how sometimes you have to step away to move a project on. I'll share how we dropped important features many of us that use _s added back in. How we need to start bringing those back.

The tale of Sass in _s is one that follows my own journey in Sass in many ways. I've learnt to rely heavily on some things and drop other parts. My journey reflects a lot of people's. Sass is part of my life creating themes for millions of people on WordPress.com. I'll bring the insight this has give me and how my work with a theme pattern library has evolved my thinking about Sass.

Nobody said open source was easy. They certainly didn't say Sass workflows were a one-size fits all. The tale of Sass in an open source project isn't an easy one to tell. I think we can all related to it though and it shows the path of Sass in many projects.
## Speaker Info (required)
- Name      : Tammie Lister
- Location  : Brighton and Hove, UK
- Contact   : tammie@automattic.com
##### Social Media:
- Twitter   : [@karmatosed](https://twitter.com/karmatosed)
- GitHub    : [karmatosed](https://github.com/karmatosed)
- Url(s)    : [diaryofawebsite.com](http://diaryofawebsite.com)
##### Bio:

Tammie works creating themes for WordPress at Automattic. Her background is a mixture of art, development and psychology. Her passion is themes. When not making themes, she contributes back to the WordPress community and the _s project. Offline, she enjoys yoga, photography and spending time with her two labradors.
##### Photo:

![Avatar](http://www.gravatar.com/avatar/d36d2c1821af9249b69ff7f5ed60529b.png?s=500)

http://www.gravatar.com/avatar/d36d2c1821af9249b69ff7f5ed60529b.png?s=500

**Comment by elyseholladay** [comment]
Hi Tammie!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

We specifically tagged your submission Unconference not because it’s “not good enough” for the conference days, but because we believe your talk would be better suited to a smaller group or more organic setting. The Unconf is a much more hands-on environment and we hope you’ll present your submission there, so attendees can have time to really try out your tips and join in the conversation! Wordpress is definitely an underrepresented tech in the Sass community, but I am sure many people would love to learn how you work with it!

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
