### ISSUE TITLE
Meaningful metaphors for motion

### ISSUE THREAD

**Issue by secor** [SassConf/2015-austin-speaker-cfp#9]
# Meaningful metaphors for motion

Alternate titles:
- "The art of allusive animation"
- "Tying in tropes to tighten your transitions"
- "Sorting some Sassy similes to subvert stillness"
### Type of Presentation

Standard Length Talk
### Quick Pitch

CSS finally contains tools for building dynamic, exciting transitions. Animation is like any other element of design, though: if you use it recklessly, your best-case-scenario is a messy composition. More likely, you’ll have a bouncing, fading, perspective-distorting, 60-frames-per-second catastrophe. 

The best UI animations are constrained to follow a single metaphor—they tell a story and help users remember where they are, where they’re going, and how to finish what they came to your app to do. In this session, we’ll check out a few animation metaphors, how to use them, and how to build them with some sexy Sass.
### Rough Outline
1. Something quick to get the audience pumped... maybe a get everyone to look under their seats, where one lucky attendee will find keys to a braaaand neeeew caaaar!
   1. Contingent on SassConf making room in the budget for said car.
2. Storytime! Some story from my personal life about how a mixed metaphor led me down a disastrous and hilarious path... I have many. The story softens the blow for the next slide:
3. Your CSS transitions SUCK. Yeah, I said it.
   1. Pull up a site with beautiful transitions. We marvel at their beauty. Things are animating all over the place!
   2. But wait, what's the intent behind all this motion? Which elements are interactive? How does this virtual motion relate to real-world motion? How does the animation aid the interface? Nice seque to the thesis of this presentations:
4. Motion without metaphor is disruptive. It foils your attempts to help your users _do something_.
5. Let's see an example of a good metaphorical motion!
6. Categories of common metaphors
7. The smart way to control your motion metaphors in Sass (mixins! arguments! cubic bezier!). Code demo for this part... we'll do it live!
   1. One final example of a well-captured motion metaphor. It will be crazy, something you'd never use, but underscores the point: sticking to the right metaphor will make task completion easier.
## Speaker Info
- Name      : Justin Secor
- Location  : San Francisco, CA
- Contact   : justin@justinsecor.com
##### Social Media:
- Twitter   : [@secor](https://twitter.com/secor)
- Github   : [secor](https://github.com/secor)
- Url(s)    : [justinsecor.com](www.justinsecor.com)
##### Bio:

Justin Secor is a designer and developer for [Opower](http://www.opower.com), where he designs and prototypes products that help people save energy. If you see him with staring off into space, he's probably imagining new design patterns that can inform, delight, and change behaviors. If you see him with his glasses on in front of a Macbook, he’s probably prototyping those patterns with Sass, Grunt, and abundant use of the CSS transition property. If you don't see Justin at all, he's probably off drawing, climbing, or making waffles.

Other talks:
- [“The Web is Inefficient, but We can Fix It”](https://www.youtube.com/watch?v=6lsepOuIvb0)—TakeOff Conference 2014, Future of Web Design 2014 (slides [here](https://github.com/secor/presentations))  
- “Social Media ePortfolios”—Educause Learning Initiative 2012 Annual Meeting  
- “Data Visualization Tools”—Teaching, Learning, and Innovation Summer Institute 2011  
- "Student Engagement and New Media Technologies"—Georgetown University Round Table on Languages and Linguistics 2011
##### Photo:

![Avatar](https://raw.githubusercontent.com/secor/portfolio/master/assets/img/justin.jpg)

**Comment by scottkellum** [comment]
Thanks Justin, would love to see a talk on animations and it’s something I don’t think designers consider enough.

What if you drew peoples attention with a particularly awkward or bad animation instead of saying “your CSS animations suck”? This way you set the bar for what is bad and you can also revisit it later as an example of how it can be better. Shock value is a great way to get peoples attention, but awe is the best way to keep it.

Not sure what personal story you’re planning on using, but just throwing one out there of a car accident, or something with motion, and then you have an animation of it. You can be deep, dramatic, serious, and if the animation is really bad then it will illustrate how much animation matters and create a good segway into your animation talk.

**Comment by secor** [comment]
> “your CSS animations suck”

Heh, yeah, I probably wouldn't say it like this exactly, but something challenging to that effect. 

> car accident, or something with motion, and then you have an animation of it.

Love it! Great idea. I happen to have a pretty good story of how I got into a car accident in the DMV parking lot, of all places.

Thanks for the input, mate!

**Comment by scottkellum** [comment]
:+1: Let me know if you need anything. I’m a SassConf mentor so input is now part of my job description.

**Comment by misscs** [comment]
If only there were budgets for :car: :smile: 

Your rough outline is a great start to helping curators get an idea of what you plan on talking about. I think it would be even more compelling if you expand some of the points, for example, what are some sites that you plan to review? Can you share some examples of good metaphorical motion? 

Don't want you to give away your special sauce in the proposal, but would be great to get a bit more insight into the finer points of animation do's and don't an attendee will walk away with. 

While I understand the intent behind saying something challenging, I also second Scott's suggestion to go for awe instead of shock. It also upholds with our code of conduct and community guidelines.

**Comment by elyseholladay** [comment]
Hi Justin!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
